%YAML 1.2
---

aws:
        profile:  "hk-aws-toolkit"
        cctv_bucket:  "pvl-video-surveillance"
        cctv_region:  "eu-central-1"
archive:
        keep_files_days:  365
        purge_permanently:  True
        extension: tar.gz
        batch_folder_limit: 31
        glacier: True
web:
        host: 0.0.0.0
        port: 8181
        dirs:
                templates: web/templates
                root: web/ROOT
        page_size:      50
db:
        cache: data/cache.json
cache:
        expire: 1800 # seconds
